### ISSUE TITLE
[Bug] Mod cannot be downloaded by Non-Curseforge launchers

### ISSUE THREAD

**Issue by DDriggs00** [mammut53/more-babies#1]
Would it be possible to allow the mod to be used on third-party launchers? Many people do not want to use the Overwolf launcher due to privacy and data-harvesting concerns, and this restriction makes it difficult for those people to use modpacks with your mod in them, as well as discouraging pack developers from including your mod. Additionally, it makes it much more difficult to host a server with this mod. For more details, see https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by mammut53** [comment]
Yes, I agree with you. The mod grew to a point where it is for the greater good to be also available to 3rd-parties. I think it is even more important that Curse Maven and other developer tools work.
