### ISSUE TITLE
[1.18.2] No config file and crashes with config menu

### ISSUE THREAD

**Issue by Sandriell** [mammut53/more-babies#3]
"Configurable spawn chance and speed modifier"

Unable to locate any config file to change mod settings.

Attempting to use the in-game mod configurator just crashes Minecraft.

https://gist.github.com/Sandriell/5cae53a2680fa340f9e654d1002dbcdb

**Comment by mammut53** [comment]
More Babies 1.18.2 has currently no config yet. I'm working on a backport.

**Comment by mammut53** [comment]
I have uploaded the backport of 1.0.0 to CurseForge as an alpha build. You can get it [here](https://www.curseforge.com/minecraft/mc-mods/more-babies/files/4121063). Be cautious with it!
