### ISSUE TITLE
Config file to reduce spawn rate doesn't work as intended. 

### ISSUE THREAD

**Issue by itzShazo** [mammut53/more-babies#5]
Part of the BETTERMC fabric modpack, using a iron golem farm design that breaks due to baby iron golems not falling into the kill hole. Tuirned the baby iron golems spawn rate from .05 to 0.0, in both mod menu and in the config file itself. However, baby iron golems still spawn at about the same rate as before. I have restarted the server and my game client, and the effect remains.

**Comment by mammut53** [comment]
What is your version of the modpack? I test it with v15 right now and it works.

**Comment by mammut53** [comment]
Conclusion from a similar issue in Discord: This is issue is probably caused by playing on a server and trying to change the server config on the client side.
